FIX: action

diff --git a/.github/workflows/builder-images.yml b/.github/workflows/builder-images.yml
--- a/.github/workflows/builder-images.yml
+++ b/.github/workflows/builder-images.yml
@@ -5,13 +5,13 @@ on:
     branches:
       - "main"
     paths:
-      - "src/pgxm/images/**"
+      - "images/**"
       - ".github/workflows/builder-images.yml"
   pull_request:
     branches:
       - "main"
     paths:
-      - "src/pgxm/images/**"
+      - "images/**"
       - ".github/workflows/builder-images.yml"
 
 permissions:
@@ -30,7 +30,7 @@ jobs:
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
-      - name: Login to Docker Hub # required for un-throttled pulls
+      - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -46,20 +46,13 @@ jobs:
       - name: Build and push image
         uses: docker/build-push-action@v6
         with:
-          context: src/pgxm/images/c-builder
+          context: images/c-builder
           push: true
           build-args: PG_VERSION=${{ matrix.pg_version }}
           platforms: linux/${{ matrix.arch }}
           tags: ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-${{ matrix.arch }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-      - name: Upload artifact
-        uses: actions/upload-artifact@v4
-        with:
-          path: ${{ runner.temp }}/image.tar
-          name: c-builder-pg${{ matrix.pg_version }}-${{ matrix.arch }}
-          overwrite: true
-          if-no-files-found: error
 
   create_and_push_c_manifests:
     needs: build_and_push_c_builders
@@ -70,28 +63,26 @@ jobs:
       matrix:
         pg_version: ["14", "15", "16", "17"]
     steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
       - name: Create and push manifest
         run: |
           set -xe
           docker manifest create \
             ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }} \
-            ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-amd64 \
-            ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-arm64
+            --amend ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-amd64 \
+            --amend ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-arm64
           docker manifest annotate ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }} \
             ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-amd64 \
             --os linux --arch amd64
@@ -102,7 +93,7 @@ jobs:
 
   build_and_push_pgrx_builders:
     needs: build_and_push_c_builders
-    name: 🦀 ${{ matrix.arch }} pgrx ${{ matrix.pgrx_versions }} on 🐘 ${{ matrix.pg_version }}
+    name: 🦀 ${{ matrix.arch }} pgrx on 🐘 ${{ matrix.pg_version }}
     runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-latest-arm64' || 'ubuntu-latest' }}
     strategy:
       fail-fast: false
@@ -134,13 +125,8 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      - name: Download c-builder
-        uses: actions/download-artifact@v4
-        with:
-          pattern: c-builder-pg${{ matrix.pg_version }}-${{ matrix.arch }}
-          path: ${{ runner.temp }}
-      - name: Load c-builder
-        run: docker load --input ${{ runner.temp }}/c-builder-pg${{ matrix.pg_version }}-${{ matrix.arch }}/image.tar
+      - name: Pull c-builder image
+        run: docker pull ghcr.io/${{ github.repository_owner }}/pgxm/c-builder:pg${{ matrix.pg_version }}-${{ matrix.arch }}
       - name: Build and push images for pgrx versions
         run: |
           set -xe
@@ -153,11 +139,11 @@ jobs:
               --push \
               --cache-from type=gha \
               --cache-to type=gha,mode=max \
-              src/pgxm/images/pgrx-builder || echo "Build failed for pgrx $version, continuing..."
+              images/pgrx-builder || echo "Build failed for pgrx $version, continuing..."
           done
 
   create_and_push_pgrx_manifests:
-    name: 🗂️ pgrx ${{ matrix.pgrx_versions }} on 🐘 ${{ matrix.pg_version }}
+    name: 🗂️ pgrx on 🐘 ${{ matrix.pg_version }}
     if: github.ref_name == 'main'
     needs: build_and_push_pgrx_builders
     runs-on: ubuntu-latest
@@ -176,21 +162,19 @@ jobs:
           - pg_version: "17"
             pgrx_versions: ["0.12.0", "0.12.1", "0.12.2", "0.12.3", "0.12.4"]
     steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
       - name: Create and push manifests
         run: |
           set -xe
